// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/features" | "/about" | "/login" | "/signup" | "/dashboard";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/features" | "/about" | "/login" | "/signup";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/loggedin/dashboard.tsx": {
    id: "routes/loggedin/dashboard";
    page: "/dashboard";
  };
};