// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/progressLine": {
    params: {};
  };
  "/editTask/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/features" | "/about" | "/login" | "/signup" | "/dashboard" | "/settings" | "/progressLine" | "/editTask/:id";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/features" | "/about" | "/login" | "/signup";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/loggedin/_layout.tsx": {
    id: "routes/loggedin/_layout";
    page: "/dashboard" | "/settings" | "/progressLine" | "/editTask/:id";
  };
  "routes/loggedin/dashboard.tsx": {
    id: "routes/loggedin/dashboard";
    page: "/dashboard";
  };
  "routes/loggedin/settings.tsx": {
    id: "routes/loggedin/settings";
    page: "/settings";
  };
  "routes/loggedin/progressLine.tsx": {
    id: "routes/loggedin/progressLine";
    page: "/progressLine";
  };
  "routes/loggedin/editTask.tsx": {
    id: "routes/loggedin/editTask";
    page: "/editTask/:id";
  };
};